######################################################################
# Automatically generated by qmake (3.0) Fri Jan 16 14:17:45 2015
######################################################################

TEMPLATE = app
INCLUDEPATH += .
LIBS += -lGL -lGLEW

# Input
SOURCES += src/*.cpp 

HEADERS += src/*.hpp
QT += widgets 
QT += opengl

OBJECTS_DIR=src/generated_files
MOC_DIR=src/generated_files
